name: Automated Build

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  TEXMFDIR: /usr/local/texlive

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: sagemath/sagemath:latest
      options: --user root
    steps:
    - name: Install tools and dependencies
      run: |
        apt-get update -y
        apt-get install -y wget git jq inkscape ghostscript imagemagick perl ruby pandoc ffmpeg
    - name: Install full TeXLive scheme
      run: |
        mkdir install-tl && cd install-tl
        wget -O - -- http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar xzf - --strip-components=1
        ./install-tl --texdir "$TEXMFDIR" --no-doc-install --no-src-install --no-interaction
        echo "$TEXMFDIR/bin/x86_64-linux/" >> $GITHUB_PATH
    - name: Install supplementary TeXLive packages
      run: |
        tlmgr repository add https://mirror.ctan.org/systems/texlive/tlcontrib tlcontrib
        tlmgr pinning add tlcontrib "*"
        tlmgr install collection-contrib
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Build document
      run: |
        cp "$(find / -name "sagetex.sty" -print -quit)" ./
        latexmk -g -f --interaction=nonstopmode
        cp out/main.pdf out/${{ github.event.repository.name }}.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LaTeX-Output
        path: out/
    - name: Check release tag
      id: check_tag
      if: github.event_name != 'pull_request'
      run: echo "::set-output name=build_tag::$(git tag -l build)"
    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      if: ${{ steps.check_tag.outputs.build_tag == 'build' }}
      with:
        tag_name: build
        files: out/${{ github.event.repository.name }}.pdf